apiVersion: v1
kind: Service
metadata:
  name: aprocache01
spec:
  ports:
  - port: 11211
#    nodePort: 11201
    targetPort: apromc-port
    protocol: TCP
  selector:
    app: apromc 
  type: ClusterIP