apiVersion: apps/v1
kind: Deployment
metadata:
  name: apromc
  labels:
    app: apromc
spec:
  selector:
    matchLabels:
      app: apromc
  replicas: 1
  template:
    metadata:
      labels:
        app: apromc
    spec:
      containers:
      - name: apromc
        image: memcached
        ports:
        - name: apromc-port
          containerPort: 11211